### ISSUE TITLE
Bad UI behavior when running into Xapian exceptions

### ISSUE THREAD

**Issue by haasn** [wangp/bower#16]
`notmuch new` is often run during the background on my system, in particular since it automatically runs whenever new mail gets delivered.

This locks the Xapian DB, which causes bad behavior in bower if bower simultaneously tries to access notmuch. I get Xapian exceptions printed directly onto the terminal, which breaks curses.

**Comment by wangp** [comment]
There was a patch on the notmuch mailing list recently to wait for the write lock instead of aborting. This problem may resolve itself in time.

Mostly. You may get error messages for failed ssh connections, for example. To be really well behaved bower should capture output from stderr (it might have useful info) then have some way to present it. For now you need to press ^L to repaint the screen.

**Comment by haasn** [comment]
I think this may have been fixed in the meantime.
