### ISSUE TITLE
Feature : selection views browsing

### ISSUE THREAD

**Issue by frediz** [wangp/bower#31]
Hi,
one feature I really miss is the possibility of having "views" that would correspond to folders I guess
in other mailers.
For example I'd like to be able to quickly switch between different views based on the limit command for example : "tag:inbox" to "tag:debian" to "tag:bugs and ~d today" etc
Maybe with shortcuts associated with those different selections.
Or a single shortcut able to cycle in a list of selections  : 
```
[command]
  views_cycle = "tag:inbox; tag:debian; tag:bugs and ~d today"
```
I don't know if it's on the roadmap and other feels the need, but I clearly often use "l" to change
my current view and change to the same kind of views.
I end up launching several bower instances each one having one specific selection and cycle through
my terminals.

F.

**Comment by wangp** [comment]
You can create search aliases with short names:
```
[bower:search_alias]
x=....
y=...
```
then switch views with `~ x <ENTER>`.

I've considered a key to immediately swap back to the previous search. `l <UP> <ENTER>` is fine enough that I haven't bothered yet.

**Comment by frediz** [comment]
Indeed for search aliases, better than nothing, but still several keys away from another search :)
I do as you do for the time being, that is, use the history to switch to another search.

**Comment by seifferth** [comment]
Sorry for replying to a thread that hasn't seen any action in years ;)

My solution to this issue has been to use single-letter aliases as well. I use `~u` for unread, for instance, and `~f` for flagged, so I am always just three keys away from one of my standard searches (`~u<Enter>` or `~f<Enter>`, for instance). Today I played around with using the Alt key for switching between these aliases. I assigned Alt+Key as kind of a shortcut for `~<Key><Enter>` and it feels pretty neat. Now I can simply use Alt+u and Alt+f for the searches mentioned above.

I believe that the user experience you get with this is pretty similar to how other applications handle views/buffers/windows (or whatever you want to call them). In irssi you can use Alt+1, Alt+2, etc. to switch between windows. Using the generalised Alt+Key one could define `~1` and `~2` as search aliases and get the same experience. I didn't see any need to limit the implementation to number keys, though.

I am not entirely sure if this is actually needed, but since the approach turned out to be really simple, and since Alt isn't used at all in the index view, I guess I might as well create a pull request.

**Comment by seifferth** [comment]
Is this still an issue, or did the Alt+Key shortcut solve it?

**Comment by wangp** [comment]
I'm happy with it. Reopen if required.
