### ISSUE TITLE
[Request] pipe messages

### ISSUE THREAD

**Issue by vivien** [wangp/bower#42]
We need a `|` binding in the thread/pager view to allow piping a given message content to a user command, e.g. `git am`.

**Comment by wangp** [comment]
Instead of a separate binding, perhaps it would make sense for open (o) to behave differently if the command begins with `|`. You can get the same effect with a helper script, e.g. call it `pipeto`
```bash
#!/bin/bash -eu
test "$#" -gt 1 || exit 1
file="${@: -1}"
test -f "$file" || exit 1
set -- "${@:1:$#-1}"
exec "$@" < "$file"
```
then open the message or part with a command `pipeto some command`.

It might be useful to gather some more use cases.

**Comment by wangp** [comment]
You can highlight a message with capital `V` (the Date line is highlighted). There's no way to execute a command on an entire thread.

**Comment by wangp** [comment]
You can highlight a message with capital `V`. There's no way to execute
a command on an entire thread.

**Comment by wangp** [comment]
I think this is adequately supported by piping thread/message IDs with `|`.
